export const PAINTS=['#edb03a','#c13c30','#c5d0cb','#294e65','#252a2f','#738770'];
export const PAINT_NAMES=['Gold','Crimson','Silver','Ocean','Graphite','Sage'];
export const PAINT_PRICE=1500,SPIN_PRICE=2000;
export const SPIN_SLOTS=[{reward:2500,chance:20},{reward:0,chance:24},{reward:3500,chance:8},{reward:0,chance:23},{reward:5000,chance:2},{reward:0,chance:23}];
export function migratePaints(data){if(data.paintVersion===1)return;const legacy=PAINTS.includes(data.paint)?data.paint:PAINTS[0];data.ownedPaints={};data.carPaint={};for(let i=0;i<5;i++){const color=data.unlocked.includes(i)?legacy:PAINTS[0];data.ownedPaints[i]=[...new Set([PAINTS[0],color])];data.carPaint[i]=color}data.paintVersion=1;data.paint=data.carPaint[data.car]}
export function carPaint(data,car){return data.carPaint?.[car]||PAINTS[0]}
export function ownsPaint(data,car,color){return data.ownedPaints?.[car]?.includes(color)===true}
// Persist the debit and outcome together before starting any cosmetic animation.
function commit(save,change){const before=JSON.parse(JSON.stringify(save.data));change(save.data);if(save.save()===false){if(save.data.statistics&&before.statistics){Object.assign(save.data.statistics,before.statistics);before.statistics=save.data.statistics}if(save.data.dailyChallenges)before.dailyChallenges=save.data.dailyChallenges;for(const key of Object.keys(save.data))delete save.data[key];Object.assign(save.data,before);return false}return true}
export function buyPaint(save,car,color){const d=save.data;if(!d.unlocked.includes(car)||!PAINTS.includes(color))return {ok:false,reason:'vehicle'};const price=ownsPaint(d,car,color)?0:PAINT_PRICE;if(d.coins<price)return {ok:false,reason:'coins'};const ok=commit(save,d=>{d.coins-=price;if(!ownsPaint(d,car,color))d.ownedPaints[car].push(color);d.carPaint[car]=color;if(d.car===car)d.paint=color});return {ok,reason:ok?'':'save',charged:ok?price:0}}
export function canSpin(data){return [0,1,2,3,4].every(id=>data.unlocked.includes(id))&&['coast','forest','city','park','alpine','harbour'].every(id=>data.unlockedMaps?.includes(id))}
export function spin(save,random=()=>{const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296}){const d=save.data;if(!canSpin(d))return {ok:false,reason:'locked'};if(d.coins<SPIN_PRICE)return {ok:false,reason:'coins'};const pick=Math.max(0,Math.min(.999999999,random()))*100;let sum=0,index=0;for(;index<SPIN_SLOTS.length-1;index++){sum+=SPIN_SLOTS[index].chance;if(pick<sum)break}const reward=SPIN_SLOTS[index].reward;const result={index,reward,number:(d.lastSpin?.number||0)+1};const ok=commit(save,d=>{d.coins+=reward-SPIN_PRICE;d.lastSpin=result;if(d.statistics)d.statistics.coins+=reward});return {ok,...result,reason:ok?'':'save'}}
