import * as T from './three.module.js';
import {damageCar} from './vehicle-models.js';
function smokeTexture(){const n=64,data=new Uint8Array(n*n*4);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const u=(x+.5)/n*2-1,v=(y+.5)/n*2-1,d=Math.hypot(u,v),i=(y*n+x)*4,edge=Math.max(0,1-d),noise=.72+.28*Math.sin(u*18)*Math.cos(v*17);data[i]=data[i+1]=data[i+2]=180;data[i+3]=Math.round(edge**1.8*noise*150)}const tex=new T.DataTexture(data,n,n);tex.needsUpdate=true;return tex}
export class CrashEffects{
 constructor(scene){this.scene=scene;this.sparkCount=90;const positions=new Float32Array(this.sparkCount*3),colors=new Float32Array(this.sparkCount*3);this.sparkGeo=new T.BufferGeometry();this.sparkGeo.setAttribute('position',new T.BufferAttribute(positions,3));this.sparkGeo.setAttribute('color',new T.BufferAttribute(colors,3));this.sparks=new T.Points(this.sparkGeo,new T.PointsMaterial({size:.09,vertexColors:true,transparent:true,opacity:1,depthWrite:false,blending:T.AdditiveBlending}));this.sparks.frustumCulled=false;scene.add(this.sparks);this.vel=[];this.shards=[];const geo=new T.BoxGeometry(.1,.025,.19);for(let i=0;i<18;i++){const m=new T.Mesh(geo,new T.MeshStandardMaterial({color:i%3?'#42474c':'#adc5ce',metalness:.6,roughness:.4}));m.castShadow=true;scene.add(m);this.shards.push(m)}const smoke=smokeTexture();this.smoke=[];for(let i=0;i<18;i++){const s=new T.Sprite(new T.SpriteMaterial({map:smoke,transparent:true,opacity:0,depthWrite:false,color:'#777b80'}));scene.add(s);this.smoke.push(s)}this.skids=[];for(let side of [-1,1]){const m=new T.Mesh(new T.PlaneGeometry(.22,4),new T.MeshBasicMaterial({color:'#101115',transparent:true,opacity:.46,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2}));m.rotation.x=-Math.PI/2;scene.add(m);m.userData.side=side;this.skids.push(m)}this.reset()}
 reset(){this.elapsed=10;this.fatal=false;this.sparks.visible=false;for(const m of [...this.shards,...this.smoke,...this.skids])m.visible=false}
 impact(car,fatal=false,side=1){this.car=car;this.fatal=fatal;this.elapsed=0;this.side=side;this.origin=new T.Vector3(car.position.x,.7,car.position.z-car.userData.length*.4);damageCar(car,fatal?1:Math.min(.7,car.userData.damage+.15));const p=this.sparkGeo.attributes.position,c=this.sparkGeo.attributes.color;for(let i=0;i<this.sparkCount;i++){p.setXYZ(i,this.origin.x,this.origin.y,this.origin.z);c.setXYZ(i,1,.45+Math.random()*.5,.08);this.vel[i]=new T.Vector3((Math.random()-.5)*9,1+Math.random()*5,(Math.random()-.3)*9)}p.needsUpdate=true;c.needsUpdate=true;this.sparks.visible=true;this.sparks.material.opacity=1;this.shards.forEach((m,i)=>{m.visible=fatal||i<5;m.position.copy(this.origin);m.rotation.set(Math.random()*3,Math.random()*3,Math.random()*3);m.userData.velocity=new T.Vector3((Math.random()-.5)*5,1+Math.random()*3,Math.random()*6-1);if(i%3===0)m.material.color.copy(car.userData.paint.color)});this.smoke.forEach(s=>s.visible=false);this.skids.forEach(m=>{m.visible=fatal;m.position.set(car.position.x+m.userData.side*.85,.047,car.position.z+1.1);m.rotation.z=side*.1})}
 update(dt){if(dt<=0||this.elapsed>8)return;this.elapsed+=dt;const t=this.elapsed,p=this.sparkGeo.attributes.position;for(let i=0;i<this.sparkCount;i++){const v=this.vel[i];v.y-=9*dt;const y=Math.max(.08,p.getY(i)+v.y*dt);if(y===.08)v.y=Math.abs(v.y)*.24;p.setXYZ(i,p.getX(i)+v.x*dt,y,p.getZ(i)+v.z*dt)}p.needsUpdate=true;this.sparks.material.opacity=Math.max(0,1-t/1.1);this.sparks.visible=t<1.1;for(const m of this.shards){if(!m.visible)continue;const v=m.userData.velocity;v.y-=9*dt;m.position.addScaledVector(v,dt);if(m.position.y<.06){m.position.y=.06;v.y=Math.abs(v.y)*.18;v.x*=.85;v.z*=.85}else{m.rotation.x+=dt*4;m.rotation.z+=dt*3}if(t>4)m.visible=false}if(this.fatal){this.smoke.forEach((s,i)=>{const age=t-i*.095;if(age<0)return;s.visible=age<5;s.position.set(this.origin.x+Math.sin(i*2.3+age)*.3+age*.12,this.origin.y+age*.65,this.origin.z+Math.cos(i*1.7)*.3);const scale=.3+age*.55;s.scale.set(scale,scale,1);s.material.opacity=Math.min(.38,age*.6)*Math.max(0,1-age/5);s.material.rotation=i+age*.13})}}
}
