// Cylinder harmonics, exhaust resonance and intake noise: no external audio downloads.
export const ENGINE_PROFILES=[
 {name:'Sport inline-four',cyl:4,idle:900,redline:6800,max:210,tone:.85,body:.48,intake:.10,order:1},
 {name:'Turbo inline-four',cyl:4,idle:850,redline:7400,max:255,tone:1,body:.38,intake:.14,order:1.12},
 {name:'Deep V6',cyl:6,idle:700,redline:6000,max:235,tone:.72,body:.56,intake:.08,order:1.3},
 {name:'Cross-plane V8',cyl:8,idle:750,redline:6800,max:295,tone:.8,body:.64,intake:.10,order:1.4},
 {name:'Smooth V12',cyl:12,idle:850,redline:8200,max:330,tone:.92,body:.38,intake:.11,order:1.65}
];
export function engineState(index,speed,throttle,boost){const p=ENGINE_PROFILES[index]||ENGINE_PROFILES[0],fraction=Math.min(1.12,Math.abs(speed)*3.6/p.max),gear=Math.min(6,1+Math.floor(fraction*5.6)),load=Math.max(0,Math.min(1,throttle));const phase=gear===1?fraction*5.6:(fraction-(gear-1)/5.6)*5.6;const rpm=Math.min(p.redline,Math.max(p.idle,p.idle+(gear===1?phase: .48+phase*.5)*(p.redline-p.idle)+(load*.035+(boost?.05:0))*(p.redline-p.idle)));return {rpm,gear,load,profile:p}}
export class AudioManager{
 constructor(save){this.save=save;this.started=false;this.car=-1;this.gear=1;this.shiftUntil=0}
 start(){if(this.started){this.ctx.resume().catch(()=>{});return}try{const c=this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=c.createGain();this.master.gain.value=0;this.limiter=c.createDynamicsCompressor();this.limiter.threshold.value=-16;this.limiter.knee.value=20;this.limiter.ratio.value=4;this.limiter.attack.value=.015;this.limiter.release.value=.25;this.master.connect(this.limiter);this.limiter.connect(c.destination);this.engineGain=c.createGain();this.engineGain.gain.value=0;this.filter=c.createBiquadFilter();this.filter.type='lowpass';this.filter.Q.value=.45;this.filter.connect(this.engineGain);this.engineGain.connect(this.master);this.exhaust=c.createOscillator();this.exhaust.connect(this.filter);this.exhaust.start();this.firing=c.createOscillator();this.firing.type='triangle';this.firingGain=c.createGain();this.firingGain.gain.value=.16;this.firing.connect(this.firingGain);this.firingGain.connect(this.filter);this.firing.start();this.body=c.createOscillator();this.body.type='sine';this.bodyGain=c.createGain();this.body.connect(this.bodyGain);this.bodyGain.connect(this.engineGain);this.body.start();const buffer=c.createBuffer(1,c.sampleRate*2,c.sampleRate),data=buffer.getChannelData(0);let last=0;for(let i=0;i<data.length;i++){last=(last+(Math.random()*2-1)*.12)/1.12;data[i]=last*3}this.noise=c.createBufferSource();this.noise.buffer=buffer;this.noise.loop=true;this.intakeFilter=c.createBiquadFilter();this.intakeFilter.type='bandpass';this.intakeFilter.Q.value=.4;this.intake=c.createGain();this.intake.gain.value=0;this.noise.connect(this.intakeFilter);this.intakeFilter.connect(this.intake);this.intake.connect(this.master);this.noise.start();this.musicGain=c.createGain();this.musicGain.gain.value=0;this.musicGain.connect(this.master);this.music=c.createOscillator();this.music.connect(this.musicGain);this.music.start();this.started=true;this.select(this.save.data.car)}catch{}}
 select(index){if(this.car===index)return;this.car=index;this.gear=1;this.shiftUntil=0;const p=ENGINE_PROFILES[index]||ENGINE_PROFILES[0],real=new Float32Array(17),imag=new Float32Array(17);for(let n=1;n<17;n++){imag[n]=Math.exp(-(n-1)/(2.3+p.tone))/Math.pow(n,1.15);if(n===p.cyl/2)imag[n]*=1.45;if(index===3&&n%2===0)imag[n]*=.82}this.exhaust.setPeriodicWave(this.ctx.createPeriodicWave(real,imag));this.bodyGain.gain.setTargetAtTime(p.body,this.ctx.currentTime,.18)}
 update(speed,active,boost,time,index=this.save.data.car,throttle=0){if(!this.started)return;this.select(index);const s=this.save.data.settings,t=this.ctx.currentTime,e=engineState(index,speed,throttle,boost),p=e.profile;if(active&&e.gear>this.gear)this.shiftUntil=t+.13;this.gear=e.gear;this.rpm=e.rpm;const set=(param,value,tau=.16)=>param.setTargetAtTime(value,t,tau);set(this.master.gain,s.master,.1);set(this.exhaust.frequency,e.rpm/120*p.order,.10);set(this.firing.frequency,e.rpm/120*p.cyl*(1+Math.sin(time*17)*.002),.10);set(this.firingGain.gain,.10+e.load*.09,.08);set(this.body.frequency,e.rpm/120*(index===3?1.01:1));set(this.filter.frequency,Math.min(1800,420+e.rpm*.12+e.load*360));set(this.engineGain.gain,active?s.engine*(.15+e.load*.14)*(t<this.shiftUntil?.72:1):0,.07);set(this.intakeFilter.frequency,350+e.rpm*.065);set(this.intake.gain,active?s.engine*p.intake*(.02+e.load*.055+(boost?.025:0)):0,.1);set(this.musicGain.gain,active?s.music*.026:0,.15);set(this.music.frequency,[110,130.81,164.81,146.83,110,164.81,130.81,98][Math.floor(time*2)%8],.1)}
 crash(){if(!this.started)return;const c=this.ctx,t=c.currentTime,b=c.createBuffer(1,c.sampleRate*.65,c.sampleRate),data=b.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.exp(-i/data.length*5);const source=c.createBufferSource(),filter=c.createBiquadFilter(),gain=c.createGain();source.buffer=b;filter.type='lowpass';filter.frequency.setValueAtTime(2400,t);filter.frequency.exponentialRampToValueAtTime(180,t+.6);gain.gain.value=this.save.data.settings.effects*.5;source.connect(filter);filter.connect(gain);gain.connect(this.master);source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect()};source.start();this.tone(48,.4,'triangle')}
 tone(freq=600,duration=.1,type='sine'){if(!this.started)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),t=this.ctx.currentTime;o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(this.save.data.settings.effects*.12,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(this.master);o.onended=()=>{o.disconnect();g.disconnect()};o.start();o.stop(t+duration)}
}
