import {T,makeCar} from './world.js';
import {reflectionEnvironment} from './visuals.js';
export class GarageView{
 constructor(){this.canvas=document.createElement('canvas');this.canvas.setAttribute('aria-label','Interactive 3D vehicle preview. Drag to rotate; use the view and zoom buttons.');this.renderer=new T.WebGLRenderer({canvas:this.canvas,antialias:true,alpha:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.2;this.scene=new T.Scene();this.environment=reflectionEnvironment(this.renderer);this.scene.environment=this.environment.texture;this.scene.add(new T.HemisphereLight('#e1f3ff','#263b32',3));for(const [x,z]of [[-5,4],[5,-3]]){const light=new T.DirectionalLight('#ffffff',3);light.position.set(x,6,z);this.scene.add(light)}this.camera=new T.PerspectiveCamera(36,1,.1,100);this.angle=-.65;this.elevation=.3;this.distance=8.5;this.cars=new Map();this.dirty=true;this.pointer=null;this.canvas.addEventListener('pointerdown',e=>{e.preventDefault();this.canvas.setPointerCapture(e.pointerId);this.pointer={id:e.pointerId,x:e.clientX,y:e.clientY}});this.canvas.addEventListener('pointermove',e=>{if(this.pointer?.id!==e.pointerId)return;this.dirty=true;this.angle-=(e.clientX-this.pointer.x)*.012;this.elevation=Math.max(.1,Math.min(.85,this.elevation+(e.clientY-this.pointer.y)*.006));this.pointer={id:e.pointerId,x:e.clientX,y:e.clientY}});for(const type of ['pointerup','pointercancel','lostpointercapture'])this.canvas.addEventListener(type,()=>this.pointer=null);this.canvas.addEventListener('contextmenu',e=>e.preventDefault());this.observer=new ResizeObserver(()=>this.resize())}
 attach(container,type,paint,tint,wheel){this.dirty=true;this.observer.disconnect();container.append(this.canvas);this.observer.observe(container);if(this.type!==type){if(this.car)this.scene.remove(this.car);this.type=type;if(!this.cars.has(type))this.cars.set(type,makeCar(paint,type,{headlights:false}));this.car=this.cars.get(type);this.scene.add(this.car)}this.car.userData.paint.color.set(paint);this.car.userData.glass.color.set('#5a7680').multiplyScalar(1-tint*.8);for(const w of this.car.userData.wheels)w.hub.material.color.set(wheel==='Black'?'#22282b':'#9da8ab');this.resize()}
 resize(){this.dirty=true;const box=this.canvas.parentElement?.getBoundingClientRect();if(!box||!box.width)return;this.renderer.setSize(box.width,box.height,false);this.camera.aspect=box.width/box.height;this.camera.updateProjectionMatrix()}
 view(name){this.dirty=true;if(name==='front')this.angle=Math.PI;if(name==='rear')this.angle=0;if(name==='side')this.angle=Math.PI/2;if(name==='reset'){this.angle=-.65;this.elevation=.3;this.distance=8.5}if(name==='in')this.distance=Math.max(5.5,this.distance-1);if(name==='out')this.distance=Math.min(12,this.distance+1)}
 render(){if(!this.canvas.isConnected||!this.dirty)return;this.dirty=false;this.camera.position.set(Math.sin(this.angle)*this.distance,1+this.distance*this.elevation,Math.cos(this.angle)*this.distance);this.camera.lookAt(0,.8,0);this.renderer.render(this.scene,this.camera)}
}
