import {needsLandscape,rotateLandscape} from './landscape.js';
import {PAINTS,PAINT_NAMES,PAINT_PRICE,SPIN_SLOTS,carPaint,ownsPaint,buyPaint,canSpin,spin} from './coin-shop.js';
import {CrowdAudio} from './crowd-audio.js';
import {TiltControls} from './tilt-controls.js';
import {DailyChallenges} from './daily-challenges.js';
import {setRoadMode} from './road-path.js';
import {World,T} from './world.js';
import {CARS,MAPS,MAP_PRICES,ownsMap,purchaseMap,formatNumber,formatDistance,awardDistanceCoins,DEFAULT_KEYS,SaveManager,InputManager,VehiclePhysics,AudioManager} from './systems.js?v=menu-polish-11';
import {Progression,ACHIEVEMENTS} from './progression.js';
import {GarageView} from './garage-view.js';
import {ENGINE_PROFILES} from './engine-audio.js';
import {TrafficManager} from './traffic.js?v=alive-12';
import {Race,RACE_DISTANCE,RACE_SCALE} from './race.js';
import {RaceView} from './race-view.js';
const raceMapName='Out Office Speedway';
let gameMode='endless',race=null,raceView=null;
const $=id=>document.getElementById(id),save=new SaveManager(),audio=new AudioManager(save),physics=new VehiclePhysics();const crowd=new CrowdAudio(audio);const progression=new Progression(save),daily=new DailyChallenges(save);let dailyToastClock=20;let world,garageView,audioThrottle=0,achievementTimer=0,hudClock=0;
try{world=new World($('world'))}catch(e){$('error').hidden=false;throw e}
world.quality(save.data.settings.quality);world.setCar(CARS[save.data.car].type,save.data.paint);const traffic=new TrafficManager(world);
let state='menu',panelKind='',returnState='menu',cameraMode=0,headlights=false,run,previewCar=save.data.car,count=0,feedbackTimer=0,shake=0,last=performance.now(),time=0,menuDistance=110,runSaved=false,crashTime=0,crashX=0,crashYaw=0;
const cameraNames=['CHASE CAM','CLOSE CHASE','HOOD CAM','CINEMATIC'];
const tilt=new TiltControls();let preparingDrive=false,tiltActive=false;const mobileControls=()=>matchMedia('(pointer:coarse)').matches||innerWidth<900;if(!['tilt','buttons'].includes(save.data.settings.mobileControl))save.data.settings.mobileControl='tilt';
function syncMobileControls(){tiltActive=mobileControls()&&save.data.settings.mobileControl==='tilt'&&tilt.ready;document.body.classList.toggle('tilt-controls',tiltActive);input.clear()}
const input=new InputManager(save.data.keys,action,()=>state==='playing'||state==='countdown'||(state==='paused'&&panelKind==='pause'));
function activeMap(){return race?'race':save.data.settings.map}
function mapName(id){return id==='race'?raceMapName:MAPS[id]}
function freshRun(){return {score:0,distance:0,coins:0,topSpeed:0,near:0,overtakes:0,combo:1,comboTimer:0,chain:0,milestonesPaid:0}}
run=freshRun();
function action(a){if(a==='blur'){if(state==='playing'||state==='countdown')pause();return}if(a==='pause'){if($('panel').open){closePanel();return}if(state==='playing'||state==='countdown')pause();return}if(state!=='playing')return;if(a==='camera')cameraMode=(cameraMode+1)%4;if(a==='horn')audio.tone(165,.4,'sawtooth');if(a==='lights')headlights=!headlights;}

function customize(){world.player.userData.paint.color.set(save.data.paint);world.player.userData.glass.color.set('#5a7680').multiplyScalar(1-save.data.tint*.8);for(let w of world.player.userData.wheels)w.hub.material.color.set(save.data.wheel==='Black'?'#22282b':'#9da8ab')}
function updateMenu(){updateMapPicker();updateDailyBadge();if($('spinBadge'))$('spinBadge').textContent=canSpin(save.data)?'2,000 COINS':'COLLECT ALL CARS & MAPS';const c=CARS[save.data.car];$('bestMenu').textContent=formatNumber(save.data.best);$('coinsMenu').textContent=formatNumber(save.data.coins);$('selectedName').textContent=c.name;$('carDescription').textContent=c.desc;$('menuTopSpeed').textContent=c.speed;customize()}
function screen(mode){const menu=mode==='menu';$('menuLayout').hidden=!menu;if(menu)world.camera.setViewOffset(innerWidth,innerHeight,-innerWidth*.18,0,innerWidth,innerHeight);else world.camera.clearViewOffset();$('menu').hidden=!menu;$('menuFooter').hidden=!menu;$('carLabel').hidden=!menu;$('hud').hidden=menu;$('pauseButton').hidden=menu;$('touch').hidden=menu||!(matchMedia('(pointer:coarse)').matches||innerWidth<900);document.body.classList.toggle('driving',!menu);if(menu)document.body.classList.remove('race-driving');placeStatusDock();if(!menu&&gameMode==='race'){$('achievementToast').hidden=true;achievementTimer=0}}
async function start(){if(preparingDrive)return;if(portraitMobile()){showLandscape(start);return;}clearCrashUI();if(gameMode!=='race'&&!ownsMap(save.data,save.data.settings.map)){if($('panel').open)$('panel').close();state='menu';screen('menu');updateMenu();return}if(mobileControls()&&save.data.settings.mobileControl==='tilt'){preparingDrive=true;try{if(!await tilt.enable()){save.data.settings.mobileControl='buttons';save.save()}}finally{preparingDrive=false}}if(portraitMobile()){showLandscape(start);return}syncMobileControls();tilt.calibrate();if($('panel').open)$('panel').close();input.clear();world.setCar(CARS[save.data.car].type,save.data.paint);customize();physics.reset();physics.x=gameMode==='race'?0:1.75;world.player.scale.setScalar(RACE_SCALE);setRoadMode(gameMode);run=freshRun();daily.newRun();run.mode=gameMode;runSaved=false;world.map=gameMode==='race'?'race':save.data.settings.map;traffic.reset();raceView?.dispose();raceView=null;race=null;if(gameMode==='race'){race=new Race(CARS[save.data.car],'race',save.data.settings);raceView=new RaceView(world,race);raceView.update(0,0)}world.player.position.set(physics.x,0,0);world.player.rotation.y=0;state='countdown';count=3.2;screen('playing');document.body.classList.toggle('race-driving',gameMode==='race');$('countdown').hidden=false;$('countdown').textContent='3';audio.start();$('bestHud').textContent='BEST '+formatNumber(save.data.best);document.activeElement?.blur();if(!race)for(let i=0;i<5;i++)traffic.spawn(0);cameraMode=0;feedbackTimer=0;message('');world.camera.position.set(1.75,4.6,10);world.camera.lookAt(1.75,.8,-22)}
function bank(){if(runSaved)return;if(run.mode!=='race')save.data.best=Math.max(save.data.best,Math.floor(run.score));save.data.coins+=run.coins;progression.flush();runSaved=true}
function home(){setRoadMode('endless');clearCrashUI();bank();raceView?.dispose();raceView=null;race=null;if($('panel').open)$('panel').close();state='menu';input.clear();screen('menu');$('countdown').hidden=true;traffic.reset();world.setCar(CARS[save.data.car].type,save.data.paint);updateMenu()}
function openPanel(kind){daily.flush();progression.flush();input.clear();panelKind=kind;returnState=state;if(state==='playing'||state==='countdown')state='paused';renderPanel();if(!$('panel').open)$('panel').showModal()}
function closePanel(){if(panelKind==='pause'&&portraitMobile()){showLandscape(closePanel);return}input.binding=null;if(panelKind==='pause'){state=pausedFrom==='countdown'?'countdown':'playing'}else if(panelKind==='settings'&&(returnState==='paused'||returnState==='playing'||returnState==='countdown')){panelKind='pause';renderPanel();return}else if(panelKind==='results'){home();return}else if(state==='paused'){state=returnState}if(panelKind==='garage'){world.setCar(CARS[save.data.car].type,save.data.paint);updateMenu()}$('panel').close();input.clear();if(tiltActive)tilt.calibrate()}
let pausedFrom='playing';function pause(){if(state!=='playing'&&state!=='countdown')return;pausedFrom=state;openPanel('pause')}
function message(text){$('feedback').textContent=text;feedbackTimer=text?2:0;$('feedback').style.opacity=text?1:0}
function earnDriving(amount){progression.earn(amount);daily.record('coins',amount)}
function event(type,severity){if(type==='health')daily.record('health');if(type==='collision')daily.collision();if(type==='near'||type==='extreme')daily.record('near');if(type==='health'){progression.stats.healthPacks++;audio.tone(740,.22);message(severity>0?`+${formatNumber(severity)} HEALTH`:'HEALTH FULL');return}if(type==='collision'){progression.stats.collisions++;run.combo=1;run.chain=0;run.comboTimer=0;shake=.5;audio.tone(65,.35,'sawtooth');message(severity>35?'HEAVY IMPACT':'CONTACT · KEEP GOING');if(physics.health<=0)endRun();return}if(type==='coin'){run.coins+=10;earnDriving(10);physics.nitro=Math.min(100,physics.nitro+7);run.score+=50*run.combo;audio.tone(990,.12);message('+10 COINS');return}run.overtakes++;progression.stats.overtakes++;run.chain++;run.combo=Math.min(8,1+Math.floor(run.chain/3));run.comboTimer=6;const near=type==='near'||type==='extreme';if(near){run.near++;physics.nitro=Math.min(100,physics.nitro+(type==='extreme'?20:12));const reward=type==='extreme'?20:10;run.coins+=reward;earnDriving(reward);progression.stats.near++}const points=(type==='extreme'?500:type==='near'?250:physics.speed>45?150:75)*run.combo;run.score+=points;audio.tone(near?820:520,.09);if(near){message(`${type==='extreme'?'EXTREME NEAR MISS +20':'NEAR MISS +10'} COINS`);return}message(`${type==='extreme'?'EXTREME NEAR MISS':near?'NEAR MISS':physics.speed>45?'FAST OVERTAKE':'OVERTAKE'}  +${formatNumber(points)}`)}
function clearCrashUI(){$('crashOverlay').hidden=true;document.body.classList.remove('crashing');crashTime=0}
function endRun(){if(state==='over'||state==='crashing')return;state='crashing';progression.stats.crashes++;run.newBest=run.score>save.data.best;if(race){run.raceDNF=true;run.racePosition=race.position(run.distance);run.raceTime=race.time}bank();input.clear();physics.boost=false;crashTime=0;crashX=physics.x;crashYaw=physics.roadYaw;cameraMode=3;world.player.visible=true;audio.crash?.();$('countdown').hidden=true;$('hud').hidden=true;$('touch').hidden=true;$('pauseButton').hidden=true;$('crashOverlay').hidden=false;document.body.classList.add('crashing')}
function finishCrash(){if(state!=='crashing')return;state='over';physics.speed=0;clearCrashUI();panelKind='results';returnState='over';renderPanel();if(!$('panel').open)$('panel').showModal()}
function bind(id,fn){$(id)?.addEventListener('click',fn)}
function renderPanel(){const p=$('panelContent');$('panelKicker').textContent=panelKind==='garage'?`YOUR GARAGE · ◈ ${formatNumber(save.data.coins)} COINS`:'OUT OFFICE';
 if(panelKind==='pause'){p.innerHTML=`<h2>PAUSED</h2><div class="pause-actions"><button id="resume" class="primary">${document.querySelector('#playButton .ui-icon').outerHTML}<span>Resume drive</span></button><button id="restart" class="plain"><svg class="ui-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 3v6h6L7.7 6.7A7 7 0 1 1 5 12H2a10 10 0 1 0 3.5-7.6z"/></svg><span>Restart</span></button><button id="pauseSettings" class="plain">${document.querySelector('#settingsButton .ui-icon').outerHTML}<span>Settings</span></button><button id="pauseHome" class="plain"><svg class="ui-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m12 2 11 9h-3v11h-6v-7h-4v7H4V11H1z"/></svg><span>Main menu</span></button></div>`;bind('resume',closePanel);bind('restart',()=>{bank();start()});bind('pauseSettings',()=>{panelKind='settings';returnState='paused';renderPanel()});bind('pauseHome',home)}
 else if(panelKind==='results'&&run.mode==='race'){renderRaceResults(p)}
 else if(panelKind==='results'){p.innerHTML=`<h2>${run.newBest?'A NEW PERSONAL BEST.':'RUN OVER.'}</h2><div class="big-score">${formatNumber(run.score)}</div><small>RUN SCORE · BEST ${formatNumber(save.data.best)}</small><div class="result-grid"><div><small>DISTANCE</small><b>${formatDistance(run.distance/1000)} km</b></div><div><small>TOP SPEED</small><b>${Math.round(run.topSpeed)} km/h</b></div><div><small>COINS EARNED</small><b class="gold">◈ ${formatNumber(run.coins)}</b></div><div><small>NEAR MISSES</small><b>${formatNumber(run.near)}</b></div><div><small>OVERTAKES</small><b>${formatNumber(run.overtakes)}</b></div><div><small>BEST SCORE</small><b>${formatNumber(save.data.best)}</b></div></div><div class="dialog-actions"><button class="primary" id="retry">DRIVE AGAIN <span>↗</span></button><button class="plain" id="resultGarage">GARAGE</button><button class="plain" id="resultHome">MAIN MENU</button></div>`;bind('retry',start);bind('resultHome',home);bind('resultGarage',()=>{home();previewCar=save.data.car;openPanel('garage')})}
 else if(panelKind==='help'){p.innerHTML='<h2>HOW TO PLAY</h2><p>Racing is a 10 km sprint against four identical-spec cars. Avoid barriers; the winner earns 2,500 coins. Endless mode has traffic and pickups.</p><p>Hold the throttle, pick your line, and pass traffic cleanly. Close passes build your multiplier and refill nitro. Heavy impacts end your run when health reaches zero.</p><div class="key-grid">'+Object.entries({throttle:'Accelerate',brake:'Brake / reverse',left:'Steer left',right:'Steer right',nitro:'Nitro boost',handbrake:'Handbrake',camera:'Change camera',horn:'Horn',lights:'Headlights'}).map(([k,v])=>`<div>${v}<kbd>${keyLabel(save.data.keys[k])}</kbd></div>`).join('')+'<div>Pause / resume<kbd>SPACE</kbd></div><div>Exit fullscreen<kbd>ESC</kbd></div></div><p>Arrow keys also work. On mobile, rotate to landscape to play. Portrait pauses the game. Tilt mode accelerates automatically: tilt to steer, hold Brake to slow, and hold Nitro to boost. Settings → Mobile controls switches back to normal steering and gas buttons. Hold your phone comfortably when starting or resuming to centre the steering. Gamepad: left stick to steer, triggers for throttle/brake, A for nitro, Y for camera and Start to pause.</p><button class="primary" id="helpDrive">LET’S DRIVE <span>↗</span></button>';bind('helpDrive',start)}
 else if(panelKind==='about'){p.innerHTML='<h2>ABOUT OUT OFFICE</h2><p>Leave the everyday behind and find your rhythm on the open road. Out Office is an arcade driving game with endless and 10 km racing modes about speed, precision, and beating your personal best.</p><p>Explore four free maps: Pacific Coast, Greenwood Forest, Metro City, and Motor Park. Preview Alpine Pass and Neon Harbour, then unlock them with earned coins to drive there. Collect glowing + pickups to restore 25 health when you’re running low. Overtake traffic, collect coins, and earn 50 coins for every 2 km you drive. Close passes refill nitro and build your score multiplier.</p><p>Use your coins to unlock five vehicles and customize your ride. Your scores, coins, vehicles, and preferences are saved in this browser.</p><button class="primary" id="aboutDone">BACK TO MENU <span>↗</span></button>';bind('aboutDone',closePanel)}
 else if(panelKind==='achievements')renderAchievements(p);
 else if(panelKind==='statistics')renderStatistics(p);
 else if(panelKind==='daily')renderDaily(p);
 else if(panelKind==='spin')renderSpin(p);
 else if(panelKind==='garage')renderGarage(p);
 else if(panelKind==='settings')renderSettings(p);
}
function finishRace(){if(state!=='playing')return;run.racePosition=race.position(run.distance);daily.raceFinished(run.racePosition);run.raceTime=race.playerFinish;const prize=race.claimPrize();run.coins+=prize;if(prize)earnDriving(prize);run.racePrize=prize;bank();state='over';physics.speed=0;input.clear();$('touch').hidden=true;$('pauseButton').hidden=true;panelKind='results';returnState='over';renderPanel();$('panel').showModal()}
function renderRaceResults(p){p.innerHTML=`<h2>${run.raceDNF?'RACE ENDED':run.racePosition===1?'RACE WON':'RACE COMPLETE'}</h2><div class="big-score">${run.raceDNF?'DNF':run.racePosition+' / 5'}</div><div class="result-grid"><div><small>RACE TIME</small><b>${(run.raceTime||0).toFixed(1)} s</b></div><div><small>DISTANCE</small><b>${formatDistance(Math.min(run.distance,RACE_DISTANCE)/1000)} km</b></div><div><small>WINNER REWARD</small><b class="gold">${formatNumber(run.racePrize||0)} COINS</b></div></div><div class="dialog-actions"><button id="retry" class="primary">RACE AGAIN</button><button id="resultHome" class="plain">MAIN MENU</button></div>`;bind('retry',start);bind('resultHome',home)}
function keyLabel(k){return k.replace('Key','').replace('Digit','').replace('Arrow','').replace('Left','').replace('Right','')}
function renderGarage(p){const c=CARS[previewCar],owned=save.data.unlocked.includes(previewCar);p.innerHTML=`<h2>SELECT VEHICLE</h2><div class="garage-grid">${CARS.map((c,i)=>`<button data-car="${i}" class="vehicle-card ${i===previewCar?'selected':''}"><small>0${i+1} / ${i===save.data.car?'SELECTED':save.data.unlocked.includes(i)?'OWNED':'LOCKED'}</small><b>${c.name}</b><span>${save.data.unlocked.includes(i)?i===save.data.car?'SELECTED':'SELECT':'◈ '+formatNumber(c.price)}</span></button>`).join('')}</div><div class="garage-preview" id="garagePreview"></div><div class="inspection-controls"><span>DRAG TO ROTATE · ${ENGINE_PROFILES[previewCar].name.toUpperCase()}</span><div>${[['front','Front'],['side','Side'],['rear','Rear'],['in','Zoom +'],['out','Zoom −'],['reset','Reset view']].map(([view,label])=>`<button class="plain" data-view="${view}">${label}</button>`).join('')}</div></div><div class="garage-details"><div><h2>${c.name.toUpperCase()}</h2><p>${c.desc}</p>${[['TOP SPEED',c.speed/350,`${c.speed} km/h`],['ACCELERATION',c.accel/17,''],['HANDLING',c.handling/1.3,''],['BRAKING',c.brake/35,''],['NITRO',c.nitro/1.5,'']].map(([n,v,t])=>`<div class="stat">${n} ${t}<span><i style="width:${v*100}%"></i></span></div>`).join('')}</div><div><small>BODY PAINT</small><div class="swatches">${PAINTS.map((color,i)=>`<button aria-label="${PAINT_NAMES[i]} · ${ownsPaint(save.data,previewCar,color)?'Owned':'1,500 coins'}" title="${PAINT_NAMES[i]} · ${ownsPaint(save.data,previewCar,color)?'Owned':'1,500 coins'}" data-color="${color}" class="swatch ${color===carPaint(save.data,previewCar)?'selected':''}" style="background:${color}">${ownsPaint(save.data,previewCar,color)?'✓':'+'}</button>`).join('')}</div><p class="paint-note">Stock paint included. New colours: 1,500 coins each, per car.</p><div id="paintOffer" role="status"></div><label class="setting-row">Wheel finish<select id="wheel"><option>Alloy</option><option>Black</option></select></label><label class="setting-row">Window tint<input id="tint" type="range" min="0" max=".9" step=".1" value="${save.data.tint}"></label><p>Earn coins from pickups, close passes, and distance challenges.</p></div></div><div class="dialog-actions"><button class="primary" id="selectCar" ${!owned&&save.data.coins<c.price?'disabled':''}>${owned?previewCar===save.data.car?'SELECTED':'SELECT':'UNLOCK FOR ◈ '+formatNumber(c.price)}<span>↗</span></button><button class="plain" id="garageDone">DONE</button></div>`;
 garageView??=new GarageView();const inspect=()=>garageView.attach($('garagePreview'),c.type,carPaint(save.data,previewCar),save.data.tint,save.data.wheel);inspect();for(const b of p.querySelectorAll('[data-view]'))b.onclick=()=>garageView.view(b.dataset.view);
 for(let b of p.querySelectorAll('[data-car]'))b.onclick=()=>{previewCar=+b.dataset.car;if(save.data.unlocked.includes(previewCar)){save.data.car=previewCar;save.data.paint=carPaint(save.data,previewCar);save.save();updateMenu()}world.setCar(CARS[previewCar].type,save.data.paint);customize();renderGarage(p)};
 for(let b of p.querySelectorAll('[data-color]'))b.onclick=()=>{const color=b.dataset.color,name=PAINT_NAMES[PAINTS.indexOf(color)];if(!owned){$('paintOffer').textContent='Unlock this vehicle before buying paint.';return}const apply=()=>{const result=buyPaint(save,previewCar,color);if(!result.ok){$('paintOffer').textContent=result.reason==='save'?'Could not save. No coins charged.':'You need 1,500 coins.';return}updateMenu();renderGarage(p);$('panelKicker').textContent=`YOUR GARAGE · ◈ ${formatNumber(save.data.coins)} COINS`};if(ownsPaint(save.data,previewCar,color)){apply();return}garageView.attach($('garagePreview'),c.type,color,save.data.tint,save.data.wheel);$('paintOffer').innerHTML=`<p>${name} preview · for ${c.name} only</p><button class="plain" id="buyPaint" ${save.data.coins<PAINT_PRICE?'disabled':''}>UNLOCK · 1,500 COINS</button>`;bind('buyPaint',apply)};
 $('wheel').value=save.data.wheel;$('wheel').onchange=e=>{save.data.wheel=e.target.value;save.save();customize();inspect()};$('tint').oninput=e=>{save.data.tint=+e.target.value;save.save();customize();inspect()};bind('selectCar',()=>{if(!owned){if(save.data.coins<c.price)return;save.data.coins-=c.price;save.data.unlocked.push(previewCar);progression.flush()}save.data.car=previewCar;save.data.paint=carPaint(save.data,previewCar);save.save();updateMenu();$('panelKicker').textContent=`YOUR GARAGE · ◈ ${formatNumber(save.data.coins)} COINS`;renderGarage(p)});bind('garageDone',closePanel)
}

let spinAnimating=false;
function renderSpin(p){const unlocked=canSpin(save.data),last=save.data.lastSpin;let angle=0;const sectors=SPIN_SLOTS.map(slot=>{const start=angle,end=angle+slot.chance*3.6;angle=end;const point=a=>[150+138*Math.sin(a*Math.PI/180),150-138*Math.cos(a*Math.PI/180)];const [x,y]=point(start),[ex,ey]=point(end),mid=(start+end)/2;return `<path d="M150 150 L${x} ${y} A138 138 0 0 1 ${ex} ${ey} Z" fill="${slot.reward?'#85bd56':'#27363d'}" stroke="#10191e" stroke-width="2"/><text transform="translate(150 150) rotate(${mid}) translate(0 -95) rotate(90)" fill="${slot.reward?'#122013':'#bac7cd'}" text-anchor="middle" dominant-baseline="middle" font-size="${slot.chance<4?9:12}" font-weight="700">${slot.reward?formatNumber(slot.reward):'EMPTY'}</text>`}).join('');
 p.innerHTML=`<h2>SPIN WHEEL</h2><p>${unlocked?'A little luck for your spare coins.':'Unlock every car and all six Endless maps to spin.'}</p><div class="spin-stage"><span class="spin-pointer" aria-hidden="true">▼</span><svg id="rewardWheel" viewBox="0 0 300 300" aria-label="Six slots: three coin prizes and three empty slots">${sectors}<circle cx="150" cy="150" r="23" fill="#10191e" stroke="#d6edc4" stroke-width="2"/><text x="150" y="154" text-anchor="middle" fill="#85ff42" font-size="10">OO</text></svg></div><p class="spin-odds">2,500 coins: 20% · 3,500: 8% · 5,000: 2%<br>Three empty slots: 70% combined. Prizes include your stake; a blank loses 2,000 coins. Coins have no cash value.</p><p id="spinResult" role="status" aria-live="polite">${last?`Last spin: ${last.reward?formatNumber(last.reward)+' coins awarded':'empty slot'}. Saved to your balance.`:'Every spin costs 2,000 coins.'}</p><p id="spinBalance">Balance: ${formatNumber(save.data.coins)} coins</p><div class="dialog-actions"><button class="primary" id="doSpin" ${!unlocked||save.data.coins<2000||spinAnimating?'disabled':''}>SPIN · 2,000 COINS</button><button class="plain" id="spinDone">DONE</button></div>`;
 bind('spinDone',closePanel);bind('doSpin',()=>{if(spinAnimating)return;const result=spin(save);if(!result.ok){$('spinResult').textContent=result.reason==='save'?'Could not save this spin. No coins charged.':'You cannot spin yet.';return}spinAnimating=true;const button=$('doSpin'),wheel=$('rewardWheel'),status=$('spinResult'),balance=$('spinBalance');button.disabled=true;status.textContent='Spinning…';const before=SPIN_SLOTS.slice(0,result.index).reduce((n,s)=>n+s.chance,0),middle=(before+SPIN_SLOTS[result.index].chance/2)*3.6;const duration=save.data.settings.motion?3600:150;wheel.style.transition=`transform ${duration}ms cubic-bezier(.12,.72,.12,1)`;const previous=Number(wheel.dataset.rotation||0),rotation=previous+1800+((360-middle-previous%360)%360);wheel.dataset.rotation=rotation;requestAnimationFrame(()=>wheel.style.transform=`rotate(${rotation}deg)`);updateMenu();setTimeout(()=>{spinAnimating=false;if(!status.isConnected){if(panelKind==='spin'&&$('panel').open)renderSpin($('panelContent'));return}status.textContent=result.reward?`${formatNumber(result.reward)} coins awarded · Net ${result.reward-2000>0?'+':''}${formatNumber(result.reward-2000)} coins`:'Empty slot · No reward this time.';balance.textContent=`Balance: ${formatNumber(save.data.coins)} coins`;button.disabled=save.data.coins<2000;if(result.reward)audio.tone(880,.22)},duration+80)});
}

function renderAchievements(p){const count=ACHIEVEMENTS.filter(a=>save.data.achievements[a.id]).length;p.innerHTML=`<h2>EVERY MILE COUNTS.</h2><p>${count} of ${ACHIEVEMENTS.length} achievements unlocked. Keep driving to build your collection.</p><div class="achievement-grid">${ACHIEVEMENTS.map(a=>{const unlocked=save.data.achievements[a.id],value=Math.min(a.target,progression.metric(a.metric));return `<article class="achievement-card ${unlocked?'earned':''}"><small>${unlocked?'✓ UNLOCKED':'IN PROGRESS'}</small><h3>${a.title}</h3><p>${a.description}</p><progress max="${a.target}" value="${value}" aria-label="${a.title}"></progress><span>${formatNumber(value)} / ${formatNumber(a.target)}${['longestRun','distance'].includes(a.metric)?' m':''}</span></article>`}).join('')}</div><button class="primary" id="progressDone">DONE <span>↗</span></button>`;bind('progressDone',closePanel)}
function renderStatistics(p){const st=progression.stats,car=progression.favourite('carDistance'),map=progression.favourite('mapDistance');const metrics=[['TOTAL DISTANCE',formatDistance(st.distance/1000)+' km'],['COINS COLLECTED',formatNumber(st.coins)],['LONGEST RUN',formatDistance(st.longestRun/1000)+' km'],['RUNS STARTED',formatNumber(st.runs)],['CRASHES · RUNS ENDED',formatNumber(st.crashes)],['COLLISIONS',formatNumber(st.collisions)],['HEALTH PACKS',formatNumber(st.healthPacks)],['NEAR MISSES',formatNumber(st.near)],['OVERTAKES',formatNumber(st.overtakes)],['TOP SPEED',formatNumber(st.topSpeed)+' km/h'],['FAVOURITE CAR',car===null?'Start driving':CARS[car]?.name||'—'],['FAVOURITE MAP',map===null?'Start driving':mapName(map)||'—']];p.innerHTML=`<h2>YOUR ROAD RECORD.</h2><p>Every escape adds up. Favourites are based on distance driven.</p><div class="lifetime-grid">${metrics.map(([label,value])=>`<div><small>${label}</small><strong>${value}</strong></div>`).join('')}</div><p class="tracking-note">Tracking since ${new Date(st.since).toLocaleDateString()}. Coins include daily rewards, race prizes, pickups, near misses and distance rewards, even after you spend them. Earlier driving history is unavailable. Saved in this browser.</p><button class="primary" id="statsDone">DONE <span>↗</span></button>`;bind('statsDone',closePanel)}

function updateDailyBadge(){const ready=daily.data.challenges.filter(c=>c.completed&&!c.claimed).length;$('dailyBadge').textContent=ready?ready+' TO CLAIM':'3 CHALLENGES'}
function renderDaily(p){daily.ensureDay();const date=daily.data.date;
 p.innerHTML=`<h2>DAILY CHALLENGES</h2><p class="daily-intro">Three new goals each day. Resets at local midnight. Rewards are yours to claim.</p><small>${date}</small><div class="daily-grid">${daily.data.challenges.map(c=>{const unit=c.unit==='km',value=unit?formatDistance(c.progress/1000):formatNumber(c.progress),target=unit?formatDistance(c.target/1000):formatNumber(c.target),detail=c.map!==undefined?MAPS[c.map]:c.car!==undefined?CARS[c.car]?.name:'';return `<article class="achievement-card daily-card ${c.completed?'earned':''}"><h3>${c.title}</h3><p>${c.description}${detail?' <b>'+detail+'</b>':''}</p><progress value="${c.progress}" max="${c.target}" aria-label="${c.title}"></progress><div class="daily-progress"><span>${value} / ${target} ${c.unit||''}</span><span class="gold">${formatNumber(c.reward)} COINS</span></div><div class="dialog-actions"><button class="${c.completed&&!c.claimed?'primary':'plain'}" data-claim="${c.id}" ${!c.completed||c.claimed?'disabled':''}>${c.claimed?'CLAIMED':c.completed?'CLAIM REWARD':'IN PROGRESS'}</button></div></article>`}).join('')}</div><div id="dailyClaimStatus" role="status" aria-live="polite"></div><div class="dialog-actions"><button class="plain" id="dailyDone">DONE</button></div>`;
 for(const b of p.querySelectorAll('[data-claim]'))b.onclick=()=>{const reward=daily.claim(b.dataset.claim,date);if(reward){progression.earn(reward);progression.flush();audio.tone(880,.18)}updateMenu();renderDaily(p);$('dailyClaimStatus').textContent=reward?formatNumber(reward)+' coins added.':'Challenges refreshed. Check today’s goals.'};bind('dailyDone',closePanel);
}
function renderSettings(p){const s=save.data.settings;p.innerHTML=`<h2>SETTINGS</h2><div class="settings-columns"><div><h3>DRIVING & DISPLAY</h3><label class="setting-row">Mobile controls<select id="mobileControl"><option value="tilt">Tilt · Auto gas</option><option value="buttons">Normal buttons / keys</option></select></label><p class="control-note" id="tiltStatus">${tilt.status}</p><label class="setting-row">Graphics<select id="quality">${['Low','Medium','High','Ultra'].map(x=>`<option>${x}</option>`).join('')}</select></label><label class="setting-row">Environment<select id="weather">${['Sunset','Night','Fog','Rain','Cycle'].map(x=>`<option>${x}</option>`).join('')}</select></label><label class="setting-row">Speed unit<select id="unitSetting"><option>km/h</option><option>mph</option></select></label><label class="setting-row">Steering sensitivity<input data-setting="sensitivity" type="range" min=".5" max="1.5" step=".05" value="${s.sensitivity}"></label><label class="setting-row">Motion effects<input data-setting="motion" type="checkbox" ${s.motion?'checked':''}></label><label class="setting-row">Automatic throttle<input data-setting="auto" type="checkbox" ${s.auto?'checked':''}></label></div><div><h3>AUDIO</h3>${['master','music','engine','effects'].map(n=>`<label class="setting-row">${n[0].toUpperCase()+n.slice(1)}<input data-setting="${n}" type="range" min="0" max="1" step=".05" value="${s[n]}"></label>`).join('')}<h3>KEY BINDINGS</h3><small>SELECT A KEY TO REBIND · SPACE PAUSES</small><div class="key-grid">${Object.entries(save.data.keys).map(([n,k])=>`<div>${n[0].toUpperCase()+n.slice(1)}<button data-key="${n}">${keyLabel(k)}</button></div>`).join('')}</div></div></div><div class="dialog-actions"><button class="primary" id="settingsDone">SAVE & RETURN <span>↗</span></button><button class="plain" id="resetKeys">RESET KEYS</button></div>`;
 $('mobileControl').value=s.mobileControl;$('mobileControl').onchange=async e=>{const choice=e.target.value;e.target.disabled=true;if(choice==='tilt'&&mobileControls()){s.mobileControl=await tilt.enable()?'tilt':'buttons'}else s.mobileControl=choice;save.save();syncMobileControls();e.target.value=s.mobileControl;e.target.disabled=false;if($('tiltStatus'))$('tiltStatus').textContent=choice==='buttons'?'On-screen steering and gas buttons enabled. Desktop keys always remain available.':tilt.status};
 for(const n of ['quality','weather']){$(n).value=s[n];$(n).onchange=e=>{s[n]=e.target.value;if(n==='quality')world.quality(s.quality);save.save()}}$('unitSetting').value=s.unit;$('unitSetting').onchange=e=>{s.unit=e.target.value;save.save()};for(let el of p.querySelectorAll('[data-setting]'))el.oninput=()=>{s[el.dataset.setting]=el.type==='checkbox'?el.checked:+el.value;save.save()};for(let b of p.querySelectorAll('[data-key]'))b.onclick=()=>{b.textContent='…';input.binding=code=>{const name=b.dataset.key,other=Object.entries(save.data.keys).find(([n,k])=>k===code&&n!==name);if(other)save.data.keys[other[0]]=save.data.keys[name];save.data.keys[name]=code;input.keys=save.data.keys;save.save();renderSettings(p)}};bind('resetKeys',()=>{save.data.keys={...DEFAULT_KEYS};input.keys=save.data.keys;save.save();renderSettings(p)});bind('settingsDone',closePanel)
}
const mapDescriptions={park:'Motor Park · Grandstands, green verges & open-road traffic',coast:'Pacific Coast · Open water & sunset skies',forest:'Greenwood Forest · A route through the pines',city:'Metro City · Skylines & city lights',alpine:'Alpine Pass · Snow-capped peaks & frosted pines',harbour:'Neon Harbour · Illuminated skyline & waterfront docks'};
function updateMapPicker(){
 const id=save.data.settings.map,owned=ownsMap(save.data,id),price=MAP_PRICES[id];
 for(const radio of document.querySelectorAll('input[name="map"]'))radio.checked=radio.value===id;
 $('mapDescription').textContent=mapDescriptions[id];$('mapCurrent').textContent=MAPS[id];
 for(const premium of ['alpine','harbour'])$(premium+'Status').textContent=ownsMap(save.data,premium)?'OWNED':formatNumber(MAP_PRICES[premium])+' COINS';
 for(const [id,label] of [['playButton','Endless'],['raceButton','Racing']]){$(id).disabled=id==='playButton'&&!owned;$(id).title=id==='raceButton'?'Race at '+raceMapName:owned?'Start '+label:'Unlock this map to play'};
 $('purchaseMap').hidden=owned;$('purchaseMap').disabled=save.data.coins<price;$('purchaseMap').textContent='UNLOCK · '+formatNumber(price)+' COINS';
 $('mapStatus').textContent=owned?(price?'OWNED · Ready to drive':''):('PREVIEW · '+(save.data.coins<price?'Earn '+formatNumber(price-save.data.coins)+' more coins to unlock.':'Unlock this map to drive.'));
}
bind('purchaseMap',()=>{if(state!=='menu')return;const result=purchaseMap(save.data,save.data.settings.map);if(!result.ok){updateMapPicker();return}progression.flush();updateMenu();audio.tone(880,.18);$('mapStatus').textContent='UNLOCKED · Ready to drive'});

for(const radio of document.querySelectorAll('input[name="map"]'))radio.onchange=()=>{if(state!=='menu'||!radio.checked)return;save.data.settings.map=radio.value;save.save();updateMapPicker()};

let landscapeIntent=null,rotatingLandscape=false;
function portraitMobile(){return needsLandscape(innerWidth,innerHeight,matchMedia('(pointer:coarse)').matches,navigator.maxTouchPoints||0)}
function refreshLandscape(){if(!$('landscapePrompt').open)return;const blocked=portraitMobile();$('rotateLandscape').textContent=blocked?'ROTATE TO LANDSCAPE':'CONTINUE';$('landscapeMessage').textContent=blocked?'Turn your phone sideways to play. Gameplay is available in landscape only.':'Ready to drive. Tap Continue when you are comfortable.'}
function showLandscape(intent){input.clear();landscapeIntent=intent;if(!$('landscapePrompt').open)$('landscapePrompt').showModal();refreshLandscape()}
function guardPortrait(){if(portraitMobile()&&(state==='playing'||state==='countdown')){pause();showLandscape(closePanel)}}
bind('rotateLandscape',async()=>{if(rotatingLandscape)return;if(!portraitMobile()){const resume=landscapeIntent;landscapeIntent=null;$('landscapePrompt').close();input.clear();tilt.calibrate();resume?.();return}rotatingLandscape=true;const button=$('rotateLandscape');button.disabled=true;try{await rotateLandscape(document,window.screen);refreshLandscape();if(portraitMobile())$('landscapeMessage').textContent='Turn your phone sideways manually. If it stays portrait, enable Auto-rotate on your phone.'}finally{rotatingLandscape=false;button.disabled=false}});
bind('landscapeBack',()=>{landscapeIntent=null;$('landscapePrompt').close();input.clear()});$('landscapePrompt').addEventListener('cancel',e=>{e.preventDefault();landscapeIntent=null;$('landscapePrompt').close()});
window.screen.orientation?.addEventListener('change',()=>{guardPortrait();refreshLandscape()});

function syncFullscreen(){const active=!!document.fullscreenElement;$('fullscreen').textContent=active?'⛶ EXIT FULLSCREEN':'⛶ FULLSCREEN';$('fullscreen').setAttribute('aria-pressed',String(active))}
bind('fullscreen',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else throw new Error('unsupported');syncFullscreen()}catch{$('fullscreen').textContent='FULLSCREEN UNAVAILABLE'}});
document.addEventListener('fullscreenchange',syncFullscreen);
bind('crashContinue',finishCrash);
bind('achievementsButton',()=>openPanel('achievements'));bind('statisticsButton',()=>openPanel('statistics'));
$('copyrightYear').textContent=new Date().getFullYear();bind('aboutButton',()=>openPanel('about'));bind('dailyButton',()=>openPanel('daily'));bind('spinButton',()=>openPanel('spin'));bind('playButton',()=>{gameMode='endless';start()});bind('raceButton',()=>{gameMode='race';start()});bind('garageButton',()=>{previewCar=save.data.car;openPanel('garage')});bind('settingsButton',()=>openPanel('settings'));bind('helpButton',()=>openPanel('help'));bind('closePanel',closePanel);bind('pauseButton',pause);bind('touchCamera',()=>action('camera'));for(const type of ['contextmenu','selectstart','dragstart'])$('touch').addEventListener(type,e=>e.preventDefault());bind('soundButton',()=>{audio.start();save.data.settings.master=save.data.settings.master>0?0:.65;save.save();$('soundButton').textContent=save.data.settings.master?'♪':'♩';$('soundButton').ariaLabel=save.data.settings.master?'Mute sound':'Enable sound'});document.querySelector('.brand').onclick=e=>{e.preventDefault();if(state==='playing'||state==='countdown')pause();else if(state==='menu')home()};$('panel').addEventListener('cancel',e=>{e.preventDefault()});
function updateHUD(){$('raceHUD').hidden=!race;if(race){$('racePosition').textContent=race.position(run.distance)+' / 5';$('raceProgress').textContent=formatDistance(Math.min(run.distance,RACE_DISTANCE)/1000)+' / 10.00 KM';$('raceTime').textContent=race.time.toFixed(1)+' s';$('raceHealth').textContent=Math.ceil(physics.health)+' HEALTH';const ahead=race.rivals.filter(r=>r.physics.health>0&&r.distance>run.distance).sort((a,b)=>a.distance-b.distance);const leader=Math.max(...race.rivals.filter(r=>r.physics.health>0).map(r=>r.distance),0);$('raceGap').textContent=ahead.length?'NEXT · '+formatNumber(ahead[0].distance-run.distance)+' m':'LEAD · '+formatNumber(Math.max(0,run.distance-leader))+' m'}$('comboBox').hidden=!!race;let kmh=Math.abs(physics.speed)*3.6;$('score').textContent=formatNumber(run.score);$('distance').innerHTML=formatDistance(run.distance/1000)+' <small>KM</small>';$('coins').textContent='◈ '+formatNumber(run.coins);$('speed').textContent=Math.round(kmh*(save.data.settings.unit==='mph'?.621371:1));$('unit').textContent=save.data.settings.unit.toUpperCase();$('gear').textContent=physics.speed<0?'R':kmh<2?'N':audio.gear||1;$('cameraName').textContent=cameraNames[cameraMode];$('rpm').style.width=Math.min(100,(audio.rpm||900)/ENGINE_PROFILES[save.data.car].redline*100)+'%';$('nitro').style.width=physics.nitro+'%';const health=Math.max(0,Math.min(100,Math.ceil(physics.health)));$('healthValue').textContent=health+'%';$('healthTrack').setAttribute('aria-valuenow',health);$('health').style.width=physics.health+'%';$('health').style.background=physics.health<35?'#f27252':'#dbe4dc';$('combo').textContent='×'+run.combo;$('comboTime').style.width=run.comboTimer/6*100+'%';$('challenge').innerHTML=race?'10 KM SPRINT <b>1st place · 2,500 coins</b>':`DISTANCE REWARD <b>Reach ${formatNumber((run.milestonesPaid+1)*2)} km · +50 coins</b>`}
function stepDrive(dt,controls){const previous=run.distance;const travelled=physics.update(dt,controls,CARS[save.data.car],tiltActive?{...save.data.settings,auto:false}:save.data.settings,run.distance);if(tiltActive)physics.speed=Math.max(0,physics.speed);run.distance+=travelled;run.score+=travelled*(1+physics.speed/60)*run.combo;run.topSpeed=Math.max(run.topSpeed,physics.speed*3.6);run.comboTimer=Math.max(0,run.comboTimer-dt);if(run.comboTimer===0){run.combo=1;run.chain=0}const distanceAward=race?0:awardDistanceCoins(run);if(distanceAward){earnDriving(distanceAward);message(`${formatNumber(run.milestonesPaid*2)} KM MILESTONE · +${formatNumber(distanceAward)} COINS`);audio.tone(1040,.3)}progression.drive(dt,travelled,run,save.data.car,activeMap());daily.drive(dt,travelled,Math.max(0,physics.speed*3.6),physics.boost,{car:save.data.car,map:activeMap()});if(race){race.update(dt,previous,run.distance,physics,severity=>{world.player.position.x=physics.x;world.crashFX.impact(world.player,physics.health<=0,1);event('collision',severity)});if(race.done&&physics.health>0)finishRace()}else traffic.update(dt,run,physics,event);progression.stats.maxCombo=Math.max(progression.stats.maxCombo,run.combo);}
const targetPos=new T.Vector3(),look=new T.Vector3();
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.15,Math.max(0,(now-last)/1000));last=now;time+=dt;guardPortrait();if($('panel').open&&!world.needsRender){audio.update(0,false,false,time);if(panelKind==='garage')garageView?.render();crowd.update(false,time);return}const playing=state==='playing',menu=state==='menu';
 if(state==='countdown'){count-=dt;let n=Math.ceil(count);$('countdown').textContent=n>0?n:'GO';if(count<-.45){state='playing';$('countdown').hidden=true;message(race?'RACE STARTED':'')}}
 if(playing){const controls=input.read();if(tiltActive){if(performance.now()-tilt.last>2500){save.data.settings.mobileControl='buttons';save.save();syncMobileControls();tilt.status='Motion signal lost. Normal buttons are enabled.';pause();return}controls.steer=tilt.read(dt);controls.throttle=controls.brake?0:1;}audioThrottle=tiltActive?controls.throttle:save.data.settings.auto?1:controls.throttle;for(let remaining=dt;remaining>0&&state==='playing';){const step=Math.min(1/60,remaining);stepDrive(step,controls);remaining-=step;}
 world.player.position.set(physics.x,Math.sin(time*20)*Math.min(.01,physics.speed*.0002),0);world.player.rotation.y=physics.roadYaw??physics.yaw;world.player.userData.body.rotation.z=physics.steer*Math.min(.055,physics.speed*.001);world.player.userData.body.rotation.x=Math.max(-.075,Math.min(.045,physics.acceleration*.002));for(let w of world.player.userData.wheels){w.pivot.rotation.y=w.front?-physics.steer*.32:0;w.wheel.rotation.x-=physics.speed*dt/.39;w.hub.rotation.x=w.wheel.rotation.x}world.player.userData.updateWheels();world.player.userData.tail.emissiveIntensity=controls.brake||controls.handbrake?5:.8;
 }
 if(raceView&&(state==='playing'||state==='countdown'))raceView.update(run.distance,playing?dt:0);
 if(state==='crashing'){crashTime+=dt;physics.speed*=Math.exp(-dt*4);const settle=1-Math.exp(-crashTime*3.4),side=physics.impactSide||1;world.player.position.set(crashX+(save.data.settings.motion?side*settle*.65:0),Math.max(0,Math.sin(crashTime*14)*.04*(1-settle)),save.data.settings.motion?settle*.8:0);world.player.rotation.y=crashYaw+(save.data.settings.motion?side*settle*.24:0);world.player.userData.body.rotation.set(-.035*settle,0,side*.022*settle);if(crashTime>(save.data.settings.motion?2.8:1.8))finishCrash()}
 if(menu){menuDistance+=dt*1.3;world.player.position.set(1.75,Math.sin(time*2)*.006,0);world.player.rotation.y=-.14;world.player.userData.body.rotation.set(0,0,0);targetPos.set(innerWidth>=900?-7.8:-6.5,innerWidth>=900?3.5:3.1,innerWidth>=900?10.6:8.8);look.set(1.3,.7,-.2)}else{const x=physics.x;switch(cameraMode){case 0:targetPos.set(x*.78,4.2,9.8+physics.speed*.025);look.set(x*.8,1,-22);break;case 1:targetPos.set(x*.9,2.4,6.5);look.set(x*.9,.9,-24);break;case 2:targetPos.set(x,1.26,-1.5);look.set(x-Math.sin(physics.roadYaw??physics.yaw)*20,1.2,-40);break;default:targetPos.set(x-6,5.4,10);look.set(x,1,-15)}if(shake>0&&save.data.settings.motion){targetPos.x+=(Math.random()-.5)*shake;targetPos.y+=(Math.random()-.5)*shake}}
 if(state==='crashing'||(state==='over'&&(!race||run.raceDNF))){targetPos.set(crashX-5.5,3.2,6.5);look.set(world.player.position.x,.75,-.6)}
 world.player.visible=cameraMode!==2||menu;const lights=headlights||world.night>.35;for(let l of world.player.userData.beams)l.intensity=lights?45:0;world.player.userData.light.emissiveIntensity=lights?4:1.5;
 const active=state==='playing'||state==='countdown',crashing=state==='crashing';world.update(menu?menuDistance:run.distance,menu||active||crashing||state==='over'?dt:0,activeMap(),race?'Sunset':save.data.settings.weather,save.data.settings.motion);
 if(active||menu||crashing){world.camera.position.lerp(targetPos,1-Math.exp(-dt*(menu?2:7)));world.camera.lookAt(look);const fov=crashing?48:menu?49:cameraMode===2?70:55+(save.data.settings.motion?physics.speed*.12+(physics.boost?6:0):0);world.camera.fov+=(fov-world.camera.fov)*dt*3;world.camera.updateProjectionMatrix()}
 shake=Math.max(0,shake-dt);$('flash').style.opacity=shake*.35;if(feedbackTimer>0&&active){feedbackTimer-=dt;$('feedback').style.opacity=Math.min(1,feedbackTimer*2)}const boosting=state==='playing'&&physics.boost;document.body.classList.toggle('boosting',boosting);$('boostBadge').hidden=!boosting;for(const flame of world.player.userData.flames){flame.visible=boosting;flame.scale.y=boosting?1.1+Math.sin(time*44)*.2:1;}document.body.classList.toggle('reduce-motion',!save.data.settings.motion);audio.update(Math.max(0,physics.speed),state==='playing',physics.boost,time,save.data.car,audioThrottle);crowd.update((!!race||activeMap()==='park')&&state==='playing',time);hudClock+=dt;if(!menu&&hudClock>=.05){updateHUD();hudClock=0}$('zoneLabel').textContent=mapName(activeMap()).toUpperCase()+' / '+(race?'10 KM RACE':state==='menu'&&!ownsMap(save.data,save.data.settings.map)?'PREVIEW':save.data.settings.map==='harbour'?'NIGHT RUN':save.data.settings.weather.toUpperCase()+' RUN');if(!$('panel').open||world.needsRender){world.render();world.needsRender=false}if($('panel').open&&panelKind==='garage')garageView?.render();dailyToastClock+=dt;achievementTimer=Math.max(0,achievementTimer-dt);if(race&&state!=='menu'){$('achievementToast').hidden=true;achievementTimer=0}else if(!achievementTimer&&progression.pending.length){$('achievementToast').textContent='ACHIEVEMENT UNLOCKED · '+progression.pending.shift();$('achievementToast').hidden=false;achievementTimer=4}else if(!achievementTimer&&state==='playing'&&daily.pending.length&&(daily.pending[0].complete||dailyToastClock>=25)){const note=daily.pending.shift();$('achievementToast').textContent=note.complete?'DAILY CHALLENGE COMPLETE · '+note.title+' · +'+note.reward+' Coins Available':'DAILY CHALLENGE · '+note.title+' · Halfway there';$('achievementToast').hidden=false;achievementTimer=5;dailyToastClock=0}else if(!achievementTimer)$('achievementToast').hidden=true;
}
addEventListener('pagehide',()=>{daily.flush();progression.flush()});
document.addEventListener('visibilitychange',()=>{if(document.hidden)daily.flush();else refreshDaily()});
function refreshDaily(){const changed=daily.ensureDay();updateDailyBadge();if(changed&&$('panel').open&&panelKind==='daily')renderDaily($('panelContent'))}
setInterval(refreshDaily,30000);
addEventListener('resize',()=>{guardPortrait();refreshLandscape();placeStatusDock();syncMobileControls();tilt.calibrate();if(state==='menu')world.camera.setViewOffset(innerWidth,innerHeight,-innerWidth*.18,0,innerWidth,innerHeight)});
function placeStatusDock(){const inFooter=innerWidth<900&&!document.body.classList.contains('driving');(inFooter?$('menuFooter'):document.body).appendChild($('statusDock'))}
$('statusDock').insertBefore($('touchCamera'),$('soundButton'));$('touchCamera').className='icon';$('touchCamera').innerHTML='<svg class="ui-icon" viewBox="0 0 24 24" aria-hidden="true"><path fill-rule="evenodd" d="M8 3h8l2 3h4v15H2V6h4zm4 5a5 5 0 1 0 0 10 5 5 0 0 0 0-10zm0 2a3 3 0 1 1 0 6 3 3 0 0 1 0-6z"/></svg>';$('touchCamera').title='Change camera view';
const desktopMap=matchMedia('(min-width:900px)');
function closeMapMenu(){ $('mapTop').classList.remove('map-open');$('mapToggle').setAttribute('aria-expanded','false');if(desktopMap.matches)$('mapPicker').hidden=true; }
function placeMapPicker(){
 if(desktopMap.matches){$('mapTop').appendChild($('mapPicker'));$('statsTop').appendChild($('menuStats'));closeMapMenu()}
 else{$('mapSlot').appendChild($('mapPicker'));$('menu').appendChild($('menuStats'));$('mapPicker').hidden=false}
}
desktopMap.addEventListener('change',placeMapPicker);placeMapPicker();
$('mapToggle').onclick=()=>{const open=$('mapToggle').getAttribute('aria-expanded')!=='true';$('mapToggle').setAttribute('aria-expanded',String(open));$('mapTop').classList.toggle('map-open',open);$('mapPicker').hidden=!open};
document.addEventListener('pointerdown',e=>{if(desktopMap.matches&&!$('mapTop').contains(e.target))closeMapMenu()});
$('mapTop').addEventListener('keydown',e=>{if(e.key==='Escape'){closeMapMenu();$('mapToggle').focus()}});



updateMenu();screen('menu');world.camera.position.set(-6.5,3.1,8.8);world.camera.lookAt(1.3,.7,-.2);requestAnimationFrame(frame);
// Expose the same session actions to browsers that support WebMCP.
if(document.modelContext?.registerTool){for(const tool of [{name:'read_drive_status',description:'Read current driving session and saved progression.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({state,score:Math.floor(run.score),distanceKm:run.distance/1000,vehicle:CARS[save.data.car].name,map:mapName(activeMap()),best:save.data.best,coins:save.data.coins})},{name:'pause_drive',description:'Pause an active driving session.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{if(state!=='playing'&&state!=='countdown')throw new Error('No active drive');pause();return {state}}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}}
