import * as T from './three.module.js';
const noiseGLSL=`float hash21(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float surfaceNoise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash21(i),hash21(i+vec2(1.,0.)),f.x),mix(hash21(i+vec2(0.,1.)),hash21(i+vec2(1.)),f.x),f.y);}`;
export function texturedMaterial(material,kind){material.onBeforeCompile=shader=>{shader.vertexShader='varying vec3 surfacePosition;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nsurfacePosition=(modelMatrix*vec4(position,1.)).xyz;');shader.fragmentShader='varying vec3 surfacePosition;\n'+noiseGLSL+'\n'+shader.fragmentShader;let code='';if(kind==='road')code=`vec2 p=surfacePosition.xz;float grain=surfaceNoise(p*140.);float patches=surfaceNoise(p*.7);float tracks=exp(-pow((abs(mod(p.x+1.75,3.5)-1.75)-.76)*8.,2.));diffuseColor.rgb*=.76+grain*.38+patches*.16-tracks*.14;`;if(kind==='ground')code=`vec2 p=surfacePosition.xz;float fine=surfaceNoise(p*7.),broad=surfaceNoise(p*.12);diffuseColor.rgb*=.64+fine*.3+broad*.4;`;if(kind==='stone')code=`vec2 p=surfacePosition.xy+surfacePosition.zz*.3;diffuseColor.rgb*=.67+surfaceNoise(p*1.4)*.23+surfaceNoise(p*.07)*.3;`;if(kind==='building')code=`vec2 p=surfacePosition.xz+surfacePosition.yy*.01;float seam=step(.95,fract(surfacePosition.y/3.5));vec2 cell=vec2(max(abs(surfacePosition.x),abs(surfacePosition.z)),surfacePosition.y);float mullion=step(.965,fract(cell.x/1.65));float pane=surfaceNoise(floor(cell/vec2(1.65,3.5)));diffuseColor.rgb*=.76+pane*.24-seam*.17-mullion*.12;`;shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\n'+code);};material.customProgramCacheKey=()=>kind;return material}
export function reflectionEnvironment(renderer){const w=512,h=256,pixels=new Uint8Array(w*h*4);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const theta=y/h*Math.PI,phi=x/w*2*Math.PI,up=Math.cos(theta),sun=Math.exp(-((phi-4.25)**2+(theta-1.32)**2)*100),band=Math.exp(-Math.abs(up)*7),r=up>0?66+band*121:38,g=up>0?105+band*70:47,b=up>0?140+band*9:40,i=(y*w+x)*4;pixels[i]=Math.min(255,r+sun*210);pixels[i+1]=Math.min(255,g+sun*180);pixels[i+2]=Math.min(255,b+sun*130);pixels[i+3]=255}for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4,phi=x/w*2*Math.PI,theta=y/h*Math.PI;const strip=Math.exp(-Math.pow((theta-.85)/.18,2))*Math.pow(Math.max(0,Math.cos(phi*3+.4)),16);for(let c=0;c<3;c++)pixels[i+c]=Math.min(255,pixels[i+c]+strip*58)}const tex=new T.DataTexture(pixels,w,h,T.RGBAFormat);tex.colorSpace=T.SRGBColorSpace;tex.mapping=T.EquirectangularReflectionMapping;tex.needsUpdate=true;const gen=new T.PMREMGenerator(renderer),result=gen.fromEquirectangular(tex);gen.dispose();tex.dispose();return result}
export function pineGeometry(radius,height,seed=0){
 const g=new T.ConeGeometry(radius,height,14,8),p=g.attributes.position,colors=[];
 for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),t=y/height+.5,a=Math.atan2(z,x);
 const tier=.87+.16*Math.cos(t*26+seed*.4),branch=1+.14*Math.sin(a*7+seed+t*12)+.06*Math.cos(a*11-t*21);
 p.setXYZ(i,x*tier*branch,y+Math.sin(a*5+seed)*height*.022*(1-t),z*tier*branch);
 const shade=.65+t*.29+.06*Math.sin(a*3+seed+t*17);colors.push(shade*.94,shade,shade*.87);
 }g.setAttribute('color',new T.Float32BufferAttribute(colors,3));g.computeVertexNormals();return g;
}
export function mountainGeometry(width,height,seed=0){
 const g=new T.PlaneGeometry(width*2,height,34,18);g.rotateX(-Math.PI/2);const p=g.attributes.position,colors=[];
 for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i),u=x/width,v=z/(height*.5),shape=Math.max(0,1-Math.abs(u)**1.5)*Math.max(0,1-Math.abs(v)**1.3);
 const ridge=.66+.16*Math.sin(u*7+seed)+.11*Math.cos(v*8+u*5),fold=Math.abs(Math.sin(u*23+v*7+seed))*.055+Math.cos(v*29-u*11)*.025;
 const elevation=shape*height*(ridge+fold)-height*.04;p.setY(i,elevation);
 const shade=.67+.25*shape+.06*Math.sin(u*27+v*11);colors.push(shade*.96,shade*.98,shade);
 }g.setAttribute('color',new T.Float32BufferAttribute(colors,3));g.computeVertexNormals();return g;
}
export function setupWater(material){const clock={value:0};material.onBeforeCompile=shader=>{shader.uniforms.waterTime=clock;shader.vertexShader='varying vec3 waterPosition;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nwaterPosition=(modelMatrix*vec4(position,1.)).xyz;');shader.fragmentShader='uniform float waterTime;varying vec3 waterPosition;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <normal_fragment_begin>',`#include <normal_fragment_begin>\nvec2 p=waterPosition.xz;vec3 waveNormal=normalize(vec3(sin(p.x*.19+p.y*.13+waterTime*.65)*.14+sin(p.x*.81-waterTime)*.06,1.,cos(p.y*.31+waterTime*.8)*.12));normal=normalize(mat3(viewMatrix)*waveNormal);`)};material.customProgramCacheKey=()=> 'water-waves';return clock}
